services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: surveys
      POSTGRES_USER: survey
      POSTGRES_PASSWORD: survey
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U survey -d surveys"]
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports: ["8000:8000"]
    volumes:
      - ./backend:/app

volumes:
  db_data:
  redis_data:
